#ddev-generated
# Add the Mailpit service
services:
  mailpit:
    container_name: "ddev-${DDEV_SITENAME}-mailpit"
    image: axllent/mailpit:v1.6.3
    networks: [default, ddev_default]
    expose:
      - ${MAILPIT_PORT:-1025}
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=${MAILPIT_UI_PORT:-8025}:${MAILPIT_UI_PORT:-8025}
      - HTTPS_EXPOSE=8026:${MAILPIT_UI_PORT:-8025}
      - MP_SMTP_BIND_ADDR=0.0.0.0:${MAILPIT_PORT:-1025}
      - MP_SMTP_RELAY_CONFIG=/tmp/config.yaml
      # Uncomment the below line after updating `./.ddev/mailpit/config.yaml` to relay ALL mail to your SMTP server.
      # - MP_SMTP_RELAY_ALL=TRUE
    volumes:
      - ./mailpit/config.yaml:/tmp/config.yaml
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
