#ddev-generated

# You must update the host with your SMTP host server.
# Mailpit will fail if a valid entry is NOT configured so an example is provided below.
host:             sandbox.smtp.mailtrap.io      # required
# port:           <port>                # optional - default 25
# starttls:       <true|false>          # optional - default false
# allow-insecure: <true|false>          # optional - default false
# auth:           <none|plain|cram-md5> # optional - default none
# username:       <username>            # required for both plain or cram-md5 auth
# password:       <password>            # required for plain auth
# secret:         <cram-secret>         # required for cram-md5 auth
# return-path:    <bounce-address>      # optional - overrides Return-Path for all released emails
